#!/bin/sh

script=$0
corepath=`dirname $script`

if [ ! -d "website" ]; then
    cp -R $corepath/website/ .
fi

if [ -f "buildout.cfg" ]; then
    echo 'Backup buildout.cfg'
    mv buildout.cfg buildout.tmp
fi

virtualenv --no-site-packages env
env/bin/easy_install zc.buildout
env/bin/buildout init
# remove buildout.cfg generated by buildout init
rm buildout.cfg

if [ -f "buildout.tmp" ]; then
    #echo 'overwrite buildout.cfg from backup'
    mv buildout.tmp buildout.cfg
fi

if [ ! -f "buildout.cfg" ]; then
    #echo 'bring in buildout.cfg from repo'
    cp $corepath/buildout.cfg .
fi

bin/buildout
